# Generated by Django 2.0 on 2017-09-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xss', '0003_xssreceiver_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xssreceiver',
            name='cookie',
            field=models.TextField(default='', verbose_name='cookie'),
        ),
        migrations.AlterField(
            model_name='xssreceiver',
            name='referer',
            field=models.TextField(default='', verbose_name='referer'),
        ),
        migrations.AlterField(
            model_name='xssreceiver',
            name='ua',
            field=models.TextField(default='', verbose_name='ua'),
        ),
    ]
