# Generated by Django 2.0 on 2017-09-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xss', '0004_auto_20170908_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='xssreceiver',
            name='Origin',
            field=models.TextField(default='', verbose_name='Origin'),
        ),
    ]
